# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0005_auto_20170125_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('results', models.BooleanField(default=False)),
                ('results_metadata', models.TextField(default='')),
            ],
        ),
    ]
