# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0006_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='task_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
