# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0007_query_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framelist', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video')),
            ],
        ),
        migrations.RemoveField(
            model_name='indexentry',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='indexentry',
            name='detection',
        ),
        migrations.RemoveField(
            model_name='indexentry',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='indexentry',
            name='video',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='tevent',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='tevent',
            name='frame',
        ),
        migrations.AddField(
            model_name='tevent',
            name='operation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='IndexEntry',
        ),
    ]
