# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0010_queryresults_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='video',
            name='key',
        ),
        migrations.AddField(
            model_name='video',
            name='dataset',
            field=models.BooleanField(default=False),
        ),
    ]
